
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: docker-registry.default.svc:5000/openshift/redhat-openjdk18-openshift:1.2 
    command: ['sh', '-c', 'sleep 4666']
    ports:
    - containerPort: 8080

